### ISSUE TITLE
Email Delete Option

### ISSUE THREAD

**Issue by rmugunda** [kirilkirkov/PHP-IMAP-Messages-Fetcher#2]
Please give a solution for email deletion on parsed mails

**Comment by kirilkirkov** [comment]
@rmugunda @tintoski here is the new function - https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/27f278c320db5a875a505239bd5f9a246113be3d

https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/027d28b51a8c1d57f4cc19527218e57db0dc6c14
