### ISSUE TITLE
how to sort

### ISSUE THREAD

**Issue by atalayxx** [kirilkirkov/PHP-IMAP-Messages-Fetcher#3]
thanks for the class.
how can I see the last message first?
ASC or DESC

**Comment by tintoski** [comment]
Sort Array $messages

**Comment by kirilkirkov** [comment]
@atalayxx  - https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/7834fc99c3da4afa3525bcea8df0016b1d775e83
