### ISSUE TITLE
HTML mail with an embedded image in gmail

### ISSUE THREAD

**Issue by tintoski** [kirilkirkov/PHP-IMAP-Messages-Fetcher#4]
HTML mail with an embedded image in gmail - not working 

<img src="cid:161e781cf592a88b1172"  ....

**Comment by kirilkirkov** [comment]
@tintoski Fixed - https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/a33cb14926bf0a5e2ed848294059f009c209e29a
