### ISSUE TITLE
Error handle

### ISSUE THREAD

**Issue by tintoski** [kirilkirkov/PHP-IMAP-Messages-Fetcher#5]
public function connect($hostname, $username, $password) {

        $connection = imap_open($hostname, $username, $password) or die('Cannot connect to Mail: ' . imap_last_error());
        if (!preg_match("/Resource.id.*/", (string) $connection)) {
            return $connection; //return error message
        }

Error message cant be returned because of "or die" in imap_open

**Comment by kirilkirkov** [comment]
Removed - https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/1328d6bc80c578dac2c549a3bc6e939a5f0bee41
