### ISSUE TITLE
empty message

### ISSUE THREAD

**Issue by tintoski** [kirilkirkov/PHP-IMAP-Messages-Fetcher#6]
Some messages have empty body.

**Comment by kirilkirkov** [comment]
@tintoski In the returned array from getMessages, body is in "'message'" key. You can send me this message that you get it with empty body to kiro2424@gmail.com to test it, if you want :)
I cant reproduce

**Comment by kirilkirkov** [comment]
![screenshot-2018-6-12 http localhost](https://user-images.githubusercontent.com/3421328/41277786-e2b40896-6e30-11e8-8478-a0077ec154b3.png)
Its work. I read you message.

**Comment by kirilkirkov** [comment]
Its readed ok.
