### ISSUE TITLE
Don't know how to save attachments

### ISSUE THREAD

**Issue by ArturPaasoja** [kirilkirkov/PHP-IMAP-Messages-Fetcher#7]
I have problems with saving attachments. My attachments doesn't save to directory and i print_r $messages out, it doesn't show attachments there either.

[attachments] => Array
                (
                )

**Comment by kirilkirkov** [comment]
Are attachments embedded? Give me headers of email

**Comment by kirilkirkov** [comment]
This commit is you fix - https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/11a9fbf7ff580d68fb1ba007ff635ef5a337cc28  or you must create attachments folder in same directory of script.

**Comment by ArturPaasoja** [comment]
Fixed, thanks :)
