### ISSUE TITLE
How to get CC'ed emails?

### ISSUE THREAD

**Issue by Parth-Kadakia** [kirilkirkov/PHP-IMAP-Messages-Fetcher#8]
Hi,

Great little plugin that works perfectly. I just wanted to know how can I retrieved who has been CC'ed in the email?

Thank you
Parth

**Comment by kirilkirkov** [comment]
Hi @Parth-Kadakia ,
Thank you. I have upload a fix for you in this commit - https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/commit/603be5a6bb54e6135131a450ea7f60871c4ded29 .
You will find ['cc'] array in messages result.

**Comment by Parth-Kadakia** [comment]
Thank you so much for such quick response.

Parth
