### ISSUE TITLE
Uncaught Error: Call to undefined function imap_open() 

### ISSUE THREAD

**Issue by led19594** [kirilkirkov/PHP-IMAP-Messages-Fetcher#9]
Hey I recently tried to use your Code in combination with the video: https://www.youtube.com/watch?v=xFQxTB0awiU.
After I typed everything correctly in (In my Opinion), I got an Error:

Fatal error: Uncaught Error: Call to undefined function imap_open() in C:\xampp\htdocs\Email-Inbox-IMAP-master\lib\class.imap.php:28 Stack trace: #0 C:\xampp\htdocs\Email-Inbox-IMAP-master\index.php(13): Imap->connect('{imap.gmail.com...', 'mygmail@gmail.c...', 'mypassword') #1 {main} thrown in C:\xampp\htdocs\Email-Inbox-IMAP-master\lib\class.imap.php on line 28

I don't know how to solve the error.

**My Project**:
[Email-Inbox-IMAP-master.zip](https://github.com/kirilkirkov/PHP-IMAP-Messages-Fetcher/files/5348927/Email-Inbox-IMAP-master.zip)

**PS:**
I replaced my gmail with a another gmail address and password (mygmail@gmail.com; mypassword)

Thank you in advance

**Comment by kirilkirkov** [comment]
@led19594 You must install IMAP extension for php . :)
